test coverage report in pr comment

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,9 +5,6 @@ name: ci-test
 
 on:
   push:
-    branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
 
 jobs:
 
@@ -51,4 +48,49 @@ jobs:
         run: make migrateup
 
       - name: Test
-        run: make test
+        run: go test -v -coverprofile=coverage.out ./...
+
+      - name: check test coverage
+        id: coverage
+        uses: vladopajic/go-test-coverage@v2
+        continue-on-error: true # Should fail after coverage comment is posted
+        with:
+          config: ./.github/.testcoverage.yml
+
+        # Post coverage report as comment (in 3 steps)
+      - name: find pull request ID
+        run: |
+          PR_DATA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+          "https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository_owner }}:${{ github.ref_name }}&state=open")
+          PR_ID=$(echo "$PR_DATA" | jq -r '.[0].number')
+
+          if [ "$PR_ID" != "null" ]; then
+          echo "pull_request_id=$PR_ID" >> $GITHUB_ENV
+          else
+          echo "No open pull request found for this branch."
+          fi
+      - name: find if coverage report is already present
+        if: env.pull_request_id
+        uses: peter-evans/find-comment@v3
+        id: fc
+        with:
+          issue-number: ${{ env.pull_request_id }}
+          comment-author: 'github-actions[bot]'
+          body-includes: 'go-test-coverage report:'
+      - name: post coverage report
+        if: env.pull_request_id
+        uses: peter-evans/create-or-update-comment@v4
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          issue-number: ${{ env.pull_request_id }}
+          comment-id: ${{ steps.fc.outputs.comment-id }}
+          edit-mode: replace
+          body: |
+            go-test-coverage report:
+            ```
+            ${{ fromJSON(steps.coverage.outputs.report) }} ```
+
+      - name: "finally check coverage"
+        if: steps.coverage.outcome == 'failure'
+        shell: bash
+        run: echo "coverage check failed" && exit 1
